name: bloc_test
description: A testing library which makes it easy to test blocs. Built to be used with the bloc state management package.
version: 0.2.1
author: Felix Angelov <felangelov@gmail.com>
repository: https://github.com/felangel/bloc
issue_tracker: https://github.com/felangel/bloc/issues
homepage: https://bloclibrary.dev

environment:
  sdk: ">=2.0.0 <3.0.0"

dependencies:
  bloc: ^0.16.0
  mockito: ^4.0.0

dev_dependencies:
  test: ">=1.3.0 <2.0.0"
  test_coverage: ^0.2.0
