name: bloc_test
description: A testing library which makes it easy to test blocs. Built to be used with the bloc state management package.
version: 3.0.1
repository: https://github.com/felangel/bloc
issue_tracker: https://github.com/felangel/bloc/issues
homepage: https://bloclibrary.dev

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  bloc: ^3.0.0
  rxdart: ^0.23.0
  mockito: ^4.0.0
  test: ^1.3.0
  meta: ^1.1.6

dev_dependencies:
  test_coverage: ^0.2.0
  effective_dart: ^1.2.0
