name: bloc_test
description: A testing library which makes it easy to test blocs. Built to be used with the bloc state management package.
version: 9.1.5
repository: https://github.com/felangel/bloc/tree/master/packages/bloc_test
issue_tracker: https://github.com/felangel/bloc/issues
homepage: https://bloclibrary.dev
documentation: https://bloclibrary.dev/#/gettingstarted
topics: [bloc, state-management, test]

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  bloc: ^8.1.1
  diff_match_patch: ^0.4.1
  meta: ^1.3.0
  mocktail: ">=0.2.0 <2.0.0"
  test: ^1.16.0

dev_dependencies:
  rxdart: ^0.27.2

screenshots:
  - description: The bloc test package logo.
    path: screenshots/logo.png
