name: angular_counter
description: A web app that uses angular_bloc

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  angular: ^6.0.0-alpha+1
  angular_bloc:
    path: ../../packages/angular_bloc

dev_dependencies:
  build_runner: ">=1.6.2 <2.0.0"
  build_web_compilers: ">=1.2.0 <3.0.0"
