name: angular_counter
description: A web app that uses angular_bloc

environment:
  sdk: ^3.10.1

dependencies:
  angular_bloc: ^10.0.0-dev.5
  bloc: ^9.1.0
  ngdart: ^8.0.0-dev.4

dev_dependencies:
  build_daemon: ^4.0.0
  build_runner: ^2.4.13
  build_web_compilers: ^4.0.0
