name: flutter_login
description: A new Flutter project.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc:
    path: ../../packages/flutter_bloc
  formz: ^0.4.0
  equatable: ^2.0.0
  authentication_repository:
    path: packages/authentication_repository
  user_repository:
    path: packages/user_repository

dependency_overrides:
  bloc:
    path: ../../packages/bloc
  flutter_bloc:
    path: ../../packages/flutter_bloc

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test:
    path: ../../packages/bloc_test
  mocktail: ^0.1.0

flutter:
  uses-material-design: true
