name: flutter_login
description: A new Flutter project.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  authentication_repository:
    path: packages/authentication_repository
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc:
    path: ../../packages/flutter_bloc
  formz: ^0.4.0
  user_repository:
    path: packages/user_repository

dependency_overrides:
  bloc:
    path: ../../packages/bloc
  flutter_bloc:
    path: ../../packages/flutter_bloc

dev_dependencies:
  bloc_test:
    path: ../../packages/bloc_test
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^3.0.1

flutter:
  uses-material-design: true
