name: hydrated_bloc
description: An extension to the bloc state management library which automatically persists and restores bloc states.
version: 9.0.0-dev.3
repository: https://github.com/felangel/bloc/tree/master/packages/hydrated_bloc
issue_tracker: https://github.com/felangel/bloc/issues
homepage: https://bloclibrary.dev
documentation: https://bloclibrary.dev/#/gettingstarted

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  bloc: ^8.1.0
  hive: ^2.0.0
  meta: ^1.3.0
  synchronized: ^3.0.0

dev_dependencies:
  test: ^1.18.2
  build_runner: ^2.1.4
  collection: ^1.15.0
  crypto: ^3.0.0
  freezed_annotation: ^0.15.0
  freezed: ^0.15.0+1
  json_serializable: ^6.0.0
  json_annotation: ^4.3.0
  mocktail: ^0.2.0
  path: ^1.8.0
  uuid: ^3.0.0
