name: hydrated_bloc
description: An extension to the bloc state management library which automatically persists and restores bloc states.
version: 10.0.0
repository: https://github.com/felangel/bloc/tree/master/packages/hydrated_bloc
issue_tracker: https://github.com/felangel/bloc/issues
homepage: https://bloclibrary.dev
documentation: https://bloclibrary.dev/getting-started
topics: [bloc, cache, state-management]
funding: [https://github.com/sponsors/felangel]

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

environment:
  sdk: ">=2.14.0 <4.0.0"

dependencies:
  bloc: ^9.0.0
  hive_ce: ^2.0.0
  meta: ^1.3.0
  synchronized: ^3.0.0

dev_dependencies:
  build_runner: ^2.3.3
  collection: ^1.17.1
  crypto: ^3.0.2
  freezed: ^2.3.2
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.0
  json_serializable: ^6.6.1
  mocktail: ^1.0.0
  path: ^1.8.3
  test: ^1.22.2
  uuid: ^3.0.7

screenshots:
  - description: The hydrated bloc package logo.
    path: screenshots/logo.png
