name: flutter_bloc
description: Flutter Widgets that make it easy to implement the BLoC (Business Logic Component) design pattern. Built to be used with the bloc state management package.
version: 2.0.0
author: Felix Angelov <felangelov@gmail.com>
repository: https://github.com/felangel/bloc
issue_tracker: https://github.com/felangel/bloc/issues
homepage: https://bloclibrary.dev

environment:
  sdk: ">=2.0.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  bloc: ^2.0.0
  provider: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  effective_dart: ^1.1.1
