name: flutter_bloc
description: Flutter Widgets that make it easy to implement the BLoC (Business Logic Component) design pattern. Built to be used with the bloc state management package.
version: 3.1.0
repository: https://github.com/felangel/bloc
issue_tracker: https://github.com/felangel/bloc/issues
homepage: https://bloclibrary.dev

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  bloc: ^3.0.0
  provider: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  effective_dart: ^1.2.0
