name: flutter_bloc
description: Flutter Widgets that make it easy to implement the BLoC (Business Logic Component) design pattern. Built to be used with the bloc state management package.
version: 8.1.3
repository: https://github.com/felangel/bloc/tree/master/packages/flutter_bloc
issue_tracker: https://github.com/felangel/bloc/issues
homepage: https://bloclibrary.dev
documentation: https://bloclibrary.dev/#/gettingstarted
topics: [bloc, state-management]

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  bloc: ^8.1.1
  flutter:
    sdk: flutter
  provider: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

screenshots:
  - description: The flutter bloc package logo.
    path: screenshots/logo.png
