name: todos_repository
description: A repository that handles todo related requests.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  todos_api:
    path: ../todos_api

dev_dependencies:
  mocktail: ^0.3.0
  test: ^1.17.0
  very_good_analysis: ^3.0.1
