name: common_github_search
description: Shared Code between AngularDart and Flutter
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0-417.1.beta <3.0.0"

dependencies:
  bloc: ^8.1.0
  equatable: ^2.0.3
  http: ^0.13.3
  stream_transform: ^2.0.0

dependency_overrides:
  bloc:
    path: ../../../packages/bloc

dev_dependencies:
  very_good_analysis: ^4.0.0
