name: example
description: A sample project that showcases how to use package:replay_bloc.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.10.1

dependencies:
  bloc: ^9.1.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.0
  replay_bloc: ^0.3.0

flutter:
  uses-material-design: true
