name: example
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc:
    path: ../../flutter_bloc
  hydrated_bloc:
    path: ../../hydrated_bloc
  replay_cubit:
    path: ../

flutter:
  uses-material-design: true
