name: flutter_form_validation
description: A new Flutter project.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc:
    path: ../../packages/flutter_bloc
  equatable: ^1.2.5
  formz: ^0.3.1

flutter:
  uses-material-design: true
