name: example
description: A new Flutter project.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  hydrated_bloc:
    path: ../
  flutter_bloc:
    path: ../../flutter_bloc
  path_provider: ^2.0.1

dependency_overrides:
  bloc:
    path: ../../bloc

flutter:
  uses-material-design: true
