name: replay_cubit
description: An extension to the cubit state management library which adds support for undo and redo.
repository: https://github.com/felangel/cubit
issue_tracker: https://github.com/felangel/cubit/issues
homepage: https://github.com/felangel/cubit

version: 0.2.0

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  cubit: ^0.1.0

dev_dependencies:
  test: ^1.14.6
  test_coverage: ^0.4.1
