name: angular_bloc
description: Angular Components that make it easy to implement the BLoC (Business Logic Component) design pattern. Built to be used with the bloc state management package.
version: 10.0.0-dev.5
repository: https://github.com/felangel/bloc/tree/master/packages/angular_bloc
issue_tracker: https://github.com/felangel/bloc/issues
homepage: https://bloclibrary.dev
documentation: https://bloclibrary.dev/getting-started
topics: [bloc, state-management]
funding: [https://github.com/sponsors/felangel]

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  bloc: ^9.0.0
  ngdart: ^8.0.0-dev.4

dev_dependencies:
  build_runner: ^2.0.0
  build_test: ^2.0.0
  build_web_compilers: ^4.0.0
  meta: ^1.8.0
  mocktail: ^1.0.0
  ngtest: ^5.0.0-dev.3
  test: ^1.16.0

screenshots:
  - description: The angular bloc package logo.
    path: screenshots/logo.png
