name: angular_bloc
description: Angular Components that make it easy to implement the BLoC (Business Logic Component) design pattern. Built to be used with the bloc state management package.
version: 2.0.0
author: Felix Angelov <felangelov@gmail.com>
repository: https://github.com/felangel/bloc
issue_tracker: https://github.com/felangel/bloc/issues
homepage: https://bloclibrary.dev

environment:
  sdk: ">=2.0.0 <3.0.0"

dependencies:
  angular: ^5.0.0
  bloc: ^2.0.0

dependency_overrides:
  package_resolver: 1.0.6
  stream_transform: 0.0.15

dev_dependencies:
  test: ">=1.3.0 <2.0.0"
  mockito: ^3.0.0
  analyzer: ^0.32.4
  build_runner: ^0.9.0
  build_test: ^0.10.2+5
  build_web_compilers: ^0.4.0+4
  source_span: ^1.4.0
  effective_dart: ^1.1.1
