name: authentication_repository
description: Dart package which manages the authentication domain.
version: 1.0.0
publish_to: none

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  cache:
    path: ../cache
  equatable: ^2.0.3
  firebase_auth: ^3.0.2
  firebase_core: ^1.5.0
  flutter:
    sdk: flutter
  google_sign_in: ^5.0.7
  meta: ^1.3.0
  very_good_analysis: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.1.4
