name: flutter_wizard
description: A new Flutter project.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  bloc: ^9.0.0
  equatable: ^2.0.0
  flow_builder: ^0.1.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.0

flutter:
  uses-material-design: true
