name: flutter_shopping_cart
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  bloc: ^6.0.1
  flutter_bloc: ^6.0.1
  equatable: ^1.2.5

flutter:
  uses-material-design: true
