name: flutter_analytics
description: An example shopping app that showcases bloc analytics logging patterns.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  analytics_repository:
    path: packages/analytics_repository
  bloc: ^8.1.1
  equatable: ^2.0.5  
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2

dev_dependencies:
  bloc_test: ^9.1.1
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^4.0.0

flutter:
  uses-material-design: true
