name: local_storage_todos_api
description: A Flutter implementation of the TodosApi that uses local storage.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.7.0
  rxdart: ^0.27.5
  shared_preferences: ^2.0.15
  todos_api:
    path: ../todos_api

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^3.0.2
