name: bloc
description: A predictable state management library that helps implement the BLoC (Business Logic Component) design pattern.
version: 8.0.3
repository: https://github.com/felangel/bloc/tree/master/packages/bloc
issue_tracker: https://github.com/felangel/bloc/issues
homepage: https://github.com/felangel/bloc
documentation: https://bloclibrary.dev

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  meta: ^1.3.0

dev_dependencies:
  mocktail: ^0.3.0
  stream_transform: ^2.0.0
  test: ^1.18.2
