name: bloc
description: A predictable state management library that helps implement the BLoC (Business Logic Component) design pattern.
version: 0.11.1
author: felix.angelov <felangelov@gmail.com>
homepage: https://felangel.github.io/bloc

environment:
  sdk: ">=2.0.0-dev.28.0 <3.0.0"

dependencies:
  meta: ^1.1.6
  rxdart: ^0.21.0

dev_dependencies:
  test: ">=1.3.0 <2.0.0"
  test_coverage: ^0.2.0
  mockito: ^4.0.0
