name: bloc
description: A predictable state management library that helps implement the BLoC (Business Logic Component) design pattern.
version: 9.0.0
repository: https://github.com/felangel/bloc/tree/master/packages/bloc
issue_tracker: https://github.com/felangel/bloc/issues
homepage: https://github.com/felangel/bloc
documentation: https://bloclibrary.dev
topics: [bloc, state-management]
funding: [https://github.com/sponsors/felangel]

environment:
  sdk: ">=2.14.0 <4.0.0"

dependencies:
  meta: ^1.3.0

dev_dependencies:
  mocktail: ^1.0.0
  stream_transform: ^2.0.0
  test: ^1.18.2

screenshots:
  - description: The bloc package logo.
    path: screenshots/logo.png
