name: bloc
description: A predictable state management library that helps implement the BLoC (Business Logic Component) design pattern.
version: 3.0.0
repository: https://github.com/felangel/bloc
issue_tracker: https://github.com/felangel/bloc/issues
homepage: https://bloclibrary.dev

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  meta: ^1.1.6
  rxdart: ^0.23.0

dev_dependencies:
  test: ">=1.3.0 <2.0.0"
  test_coverage: ^0.2.0
  mockito: ^4.0.0
  effective_dart: ^1.2.0
