name: flutter_timer
description: A new Flutter project.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  bloc: ^8.1.0
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1

dev_dependencies:
  bloc_test: ^9.0.0
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^3.1.0

dependency_overrides:
  bloc:
    path: ../../packages/bloc
  bloc_test:
    path: ../../packages/bloc_test
  flutter_bloc:
    path: ../../packages/flutter_bloc

flutter:
  uses-material-design: true
