name: flutter_infinite_list
description: A new Flutter project.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc:
    path: ../../packages/flutter_bloc
  http: ^0.12.0
  equatable: ^1.2.5
  rxdart: ^0.24.0

flutter:
  uses-material-design: true
