name: weather_repository
description: A Dart Repository which manages the weather domain.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  equatable: ^2.0.3
  json_annotation: ^4.0.0
  meta_weather_api:
    path: ../meta_weather_api

dev_dependencies:
  coverage: ^1.0.3
  build_runner: ^1.10.0
  json_serializable: ^4.0.0
  mocktail: ^0.2.0
  test: ^1.16.4
