name: flutter_bloc

on:
  push:
    paths:
      - "packages/flutter_bloc/**"
      - ".github/workflows/flutter_bloc.yaml"

  pull_request:
    paths:
      - "packages/flutter_bloc/**"
      - ".github/workflows/flutter_bloc.yaml"

jobs:
  build:
    defaults:
      run:
        working-directory: packages/flutter_bloc
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1.4.0
      - name: Install Dependencies
        run: flutter packages get
      - name: Format
        run: flutter format --set-exit-if-changed lib test example
      - name: Analyze
        run: flutter analyze lib test example
      - name: Run tests
        run: flutter test --no-pub --coverage --test-randomize-ordering-seed random
      - name: Check Code Coverage
        uses: ChicagoFlutter/lcov-cop@v1.0.0
        with:
          path: packages/flutter_bloc/coverage/lcov.info
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
