name: hydrated_bloc

on:
  push:
    paths:
      - "packages/hydrated_bloc/**"
      - ".github/workflows/hydrated_bloc.yaml"

  pull_request:
    paths:
      - "packages/hydrated_bloc/**"
      - ".github/workflows/hydrated_bloc.yaml"

jobs:
  build:
    defaults:
      run:
        working-directory: packages/hydrated_bloc
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1.4.0
      - name: Install Dependencies
        run: flutter pub get
      - name: Format
        run: flutter format --set-exit-if-changed lib test example
      - name: Analyze
        run: flutter analyze lib test example
      - name: Run tests
        run: flutter test -j 1 --no-pub --coverage --test-randomize-ordering-seed random
      - name: Check Code Coverage
        uses: VeryGoodOpenSource/very_good_coverage@v1.1.1
        with:
          path: packages/hydrated_bloc/coverage/lcov.info
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
