name: bloc_tools
description: Tools for building applications using the bloc state management library.
version: 0.1.0-dev.7
repository: https://github.com/felangel/bloc/tree/master/packages/bloc_tools
issue_tracker: https://github.com/felangel/bloc/issues
homepage: https://github.com/felangel/bloc
documentation: https://bloclibrary.dev
topics: [bloc, state-management]
funding: [https://github.com/sponsors/felangel]

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  args: ^2.1.0
  io: ^1.0.0
  mason: ^0.1.0-dev.33
  pub_updater: ^0.5.0

dev_dependencies:
  build_runner: ^2.0.0
  build_verify: ^3.0.0
  build_version: ^2.0.0
  mocktail: ^1.0.0
  test: ^1.17.0

executables:
  bloc:

screenshots:
  - description: The bloc tools package logo.
    path: screenshots/logo.png
