name: bloc_tools
description: Tools for building applications using the bloc state management library.
version: 0.1.0-dev.20
repository: https://github.com/felangel/bloc/tree/master/packages/bloc_tools
issue_tracker: https://github.com/felangel/bloc/issues
homepage: https://github.com/felangel/bloc
documentation: https://bloclibrary.dev
topics: [bloc, state-management]
funding: [https://github.com/sponsors/felangel]

environment:
  sdk: ^3.10.1

dependencies:
  args: ^2.7.0
  bloc_lint: ^0.3.5
  lsp_server_ce: ^0.4.0
  mason: ^0.1.2
  path: ^1.9.1
  pub_updater: ^0.5.0

dev_dependencies:
  build_runner: ^2.10.4
  build_verify: ^3.1.1
  build_version: ^2.1.3
  mocktail: ^1.0.4
  test: ^1.28.0

executables:
  bloc:

screenshots:
  - description: The bloc tools package logo.
    path: screenshots/logo.png
